CREATE TABLE CLIENTE{
      ID       SERIAL          PRIMARY KEY,
      NOME     VARCHAR(150)    NOT NULL,
      EMAIL    VARCHAR(100)    NOT NULL UNIQUE
};

CREATE TABLE PRODUTOS{
    ID         SERIAL          PRIMARY KEY,
    NOME       VARCHAR(150)    NOT NULL,
    PRECO      DECIMAL(10,2)   NOT NULL
};

CREATE TABLE PEDIDOS{
    ID          SERIAL         PRIMARY KEY,
    DATAHORA    TIMESTAMP      NOT NULL,
    VALOR       DECIMAL(10,2)  NOT NULL,
    CLIENTE_ID  INT            NOT NULL,
    FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(ID)
};

CREATE TABLE PEDIDOS_PRODUTOS{
    PEDIDO_ID    INT           NOT NULL,
    PRODUTO_ID   INT           NOT NULL,
    PRIMARY KEY(PEDIDO_ID, PRODUTO_ID),
    FOREIGN KEY(PEDIDO_ID) REFERENCES PEDIDOS(ID),
    FOREING KEY(PRODUTO_ID) REFERENCES PRODUTOS(ID)
};